language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-18
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-18

# By default, we get an older version of libstdc++6 so we need to update it for CMake.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6

jdk:
  - oraclejdk8

before_script:
  # Install cmake.
  - wget https://github.com/Commit451/android-cmake-installer/releases/download/1.1.0/install-cmake.sh
  - chmod +x install-cmake.sh
  - ./install-cmake.sh
  # Install the NDK.
  - pushd ~
  - wget http://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
  - unzip -qo android-ndk-r13b-linux-x86_64.zip
  - export ANDROID_NDK_HOME="$HOME/android-ndk-r13b"
  - popd
  # Create and start an emulator for instrumentation tests.
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  # We have to explicitly specify connectedCheck on the 'tests' module as it will fail if it is run
  # on the 'duktape' module, despite not actually having any androidTest sources.
  - ./gradlew clean build :tests:connectedCheck

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "BP4x4YVhnMfezSiOoxjYZFm5WpjF5Qa2RvJ841q6vj0yTCmfkyw9F8JNloQpVHgy9pIXABXaxykEV4ddPNuQ/uru/1NalPLPMOjY+S+8kNSRtwH14aLEQVPSxZp2zEuAQIzKY0tW6drh9z2pfZoCqko6cH8h+hWwLs3SGsFrAJ8hJTl3ROe/vTkOKw/Ec1FNgT667nxlK/Q2uQWA5CNvjjDIMtOOEnXKO90jdq4PIIPrbLfeusTDShjMK8ltUtFRs7P84gCKZ3HWbIVdHHzLtP700E+jllB3AID6s/wMV8ExoNXKOjwDuOpkkK48K6F23uRQ1VdCpAL+DiBALiOwqevn2Ifo6qoEBD+ZoKeb5YrK2YRkn13QbWc+1rO//NFGIZzsRI0WsnhQLDOC8PWz4uesyI5wRV7jYtG4o6rDLiwAgutJZZCSPX4YRnfgkP1Usa5F8JM9P0zg61ZbsTQC+AXkgQUNq7WrvJE9UmAJsf1M4dzYZDlpTlCqUkyDa57LYhbg4Lqk6hCCV3vRcMCtPFIZvwDPSo309zQjkhK8TZbUKx3ZoWgXphJcm9Mdmqan2wMgOzMweIJ46f5sQX5r1jPvPTDukxilnpv8ijHTxshRlHUpQp4biaFw4cAJmJtkCiL4OrKLu1gp/v/+axFiwZiTJVSFYEaAvioTVU44ic4="
    - secure: "VSUjkbwVilSXzhe9oV/2WaRZ/a3cnAMT/MrKtTaxnRPhTOg7IcLnl986Y9Spg2grP3bgzFbJbcxcDte+kuOM7xas5BLoYdbeQW7FSuaP5ATNIRknDXp6TVe2T3zIZ2iwWJRFkKy3eyYbPNbwDEwI77WbuWRUlCFkjWuMg/mMy3BtBH2bCW4riPe5h8WeW0NzJv/1XpcZyUqJRLcDM6a9V9UNnHZigQmFb87id6Jp3OKjb39M4MSEzSVuUDP4JnV7/OJetbVD1bd0PVpDb38zfbczS2lcz0EsddL76zagYxxvST0Mfi2QkKhFgDABc0QaXckR3TGGljlBScZj34shqFQ5xQnSCCFQ75HCClgCylEYPngSjPQnfRUafI+6pP6VK1dwG6kwhO5cd2UYq9lDVYcGQ6cszKDF46gjTq2/uHw5gked0ZDS3n8MTp043OsETtFzA1aqk7jhNpa4ADb89STbjRVT66SiLlfwBU4HyufexNg5RKBIeORksJB8TDN/F8aij6bPtRHeEaV99cEgQFu4H5qXchQD37DwnGiJ8nFW2/XMom2cqKcp57z5UacLezLkEV1uhdaudCCsfj0da5W3Df9n8adEOeZvJPoZN4CZaGJ50yoD9MO7XG0Lc7qBqW28DIf9ArabLL6cJrwU9EybJZqzZftslgp7yKb/vsw="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
