[versions]
androidx-compose = "1.2.0-beta02"
compileSdk = "31"
graalvm = "22.0.0.2"
kotlin = "1.6.21"
kotlinx-coroutines = "1.6.1-native-mt"
kotlinx-serialization = "1.3.3"
okHttp = "4.9.1"
okio = "3.0.0"
picocli = "4.6.3"
sqldelight = "1.5.3"
targetSdk = "31"

[libraries]
android-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version = "7.0.2" }
android-material = { module = "com.google.android.material:material", version = "1.4.0" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.4.0-alpha01" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.1.0" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version = "1.3.1" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.6.0" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.3.1" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.2.0" }
cklib-gradle-plugin = { module = "co.touchlab:cklib-gradle-plugin", version = "0.2.4" }
coil-compose = { module = "io.coil-kt:coil-compose", version = "1.3.2" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.6.21" }
duktape = { module = "com.squareup.duktape:duktape-android", version = "1.4.0" }
graal-gradle-plugin = { module = "gradle.plugin.com.palantir.graal:gradle-graal", version = "0.10.0" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
mavenPublish-gradle-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.18.0" }
okHttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
okHttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttp" }
okio-core = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakeFileSystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-compiler = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
shadowJar-gradle-plugin = { module = "gradle.plugin.com.github.johnrengelman:shadow", version = "7.1.2" }
sqldelight-gradle-plugin = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }
sqldelight-driver-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-driver-sqlite = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version = "3.34.0" }
turbine = { module = "app.cash.turbine:turbine", version = "0.6.0" }
truth = { module = "com.google.truth:truth", version = "1.0" }

[plugins]
zipline-kotlin = { id = "app.cash.zipline.kotlin" }
